name: icon-filter
ckpt_dir: '/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/data/ckpt/'
# resume_path: "./data/ckpt/icon-filter.ckpt"
# resume_path: "/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/data/ckpt/baseline/icon-filter_batch2_withnormal_debugv1_0417/last.ckpt"
# resume_path: "/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/data/ckpt/baseline/icon_pamir_perturb_smpl_01_mlpse/last.ckpt"
resume_path: "/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/data/ckpt/trainonthuman2/train2_on_thuman2_36views_icon_pamir_vol{4}_pe{12}_mlpse_start_c_1_end_c_3_spatialse_r4/last.ckpt"
normal_path: "./data/ckpt/normal.ckpt"
results_path: '/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/data/results/'

test_mode: True
batch_size: 1

net:
  mlp_dim: [256, 512, 256, 128, 1]
  res_layers: [2,3,4]
  num_stack: 2
  prior_type: "icon" # icon/pamir/icon
  use_filter: True
  in_geo: (('normal_F',3), ('normal_B',3))
  in_nml: (('image',3), ('T_normal_F',3), ('T_normal_B',3))
  smpl_feats: ['sdf', 'cmap', 'norm', 'vis']
  gtype: 'HGPIFuNet'
  norm_mlp: 'batch'
  hourglass_dim: 6
  smpl_dim: 7

# user defined
mcube_res: 256    # occupancy field resolution, higher --> more details
clean_mesh: False # if True, will remove floating pieces