name: baseline/pifu_debug
ckpt_dir: '/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/data/ckpt/'
resume_path: "./data/ckpt/pifu.ckpt"
normal_path: "./data/ckpt/normal.ckpt"
results_path: '/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/data/results/'

test_mode: True
batch_size: 1

net:
  mlp_dim: [256, 512, 256, 128, 1]
  res_layers: [2,3,4]
  num_stack: 2
  prior_type: "pifu" # icon/pamir/icon
  use_filter: True
  in_geo: (('image',3), ('normal_F',3), ('normal_B',3))
  in_nml: (('image',3), ('T_normal_F',3), ('T_normal_B',3))
  gtype: 'HGPIFuNet'
  norm_mlp: 'batch'
  hourglass_dim: 12


# user defined
mcube_res: 512    # occupancy field resolution, higher --> more details
clean_mesh: False # if True, will remove floating pieces

# _C.ckpt_dir = '/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/'+_C.name+'/ckpt/'
# _C.resume_path = ''
# _C.normal_path = ''
# _C.corr_path = ''
# _C.results_path = '/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/'+_C.name+'/results/'